== Arquillian Container Weld

Arquillian Weld embedded container is for basic testing where you can use Weld/CDI features.
Note that this container uses flat deployment structure which means that all bean deployment archives
(as well as beans XML files) are merged to one single test bean deployment archive.
Mock EE services (like EjbServices and JpaInjectionServices) are not enabled by default and you can enable them by changing Weld environment value
(see https://github.com/weld/api/blob/master/weld-spi/src/main/java/org/jboss/weld/bootstrap/api/Environments.java)
either programmatically by passing environment parameter to `TestContainer` (or `FlatDeployment` or `BeanDeploymentArchiveImpl`) or you can use configuration property.

=== Version compatibility

[cols="4*", options="header"]
|===
| *Container Version* | *Jakarta EE* | *CDI* | *Weld*
| 5.x _(planned)_ | Jakarta EE 12 | CDI 5.0 | Weld 7.0
| 4.x | Jakarta EE 11 | CDI 4.1 | Weld 6.0
| 3.x | Jakarta EE 9/10 | CDI 3.0/4.0 | Weld 4/5
| 2.x | Java EE 7 | CDI 1.2 | Weld 2.x
| 1.x | Java EE 6/7 | CDI 1.0/1.1 | Weld 1.x/2.x
|===

=== Configuration properties

[cols="3*", options="header"]
|===
| *Name* | *Description* | *Default value*
| *enableConversationScope* | enable Conversation scope | false
| *environment* | set Weld environment | SE
|===
