name: Arquillian Weld Container CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build Arq-Weld-container - JDK ${{matrix.java.name}}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - {
            name: "17",
            java-version: 17,
          }
          - {
            name: "21",
            java-version: 21,
          }
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK ${{ matrix.java.name }}
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java.java-version }}
      - name: "Build with Maven"
        run: |
          mvn clean install
