name: Arquillian Weld Container CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build Arq-Weld-container - JDK ${{matrix.java.name}}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - { name: "8",
              java-version: 8,
          }
          - {
            name: "11",
            java-version: 11,
          }
          - {
            name: "16",
            java-version: 16,
          }
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java.name }}
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ matrix.java.java-version }}
      - name: "Build with Maven"
        run: |
          mvn clean install
